add_newline = false

[fill]
symbol=' '
style='white'

[username]
format = "[$user]($style)@"
show_always = true
style_user = "bold white"

[hostname]
format = "[$hostname]($style) in "
style = "bold bright-white"
disabled = false
ssh_only = false

[conda]
style = "yellow"
ignore_base = false
symbol = " "

[cmd_duration]
disabled=true
format='\[in $duration\]'

[directory]
style="bold bright-cyan"
truncate_to_repo = true

[python]
symbol = " "

[git_branch]
symbol = " "
style="bold purple"

