add_newline = false

[fill]
symbol=" "
style="bold white"

[username]
format = "[$user@]($style)"
show_always = true
style_user = "bold green"

[hostname]
format = "[$hostname]($style) in "
style = "bold green"
disabled = false
ssh_only = false

[conda]
style = "yellow"
ignore_base = false
symbol = " "

[cmd_duration]
disabled=true

[directory]
style="bold bright-cyan"
truncate_to_repo = true

[python]
symbol = " "

[git_branch]
symbol = " "
style="bold purple"

