" Enable syntax highlighting
au BufNewFile,BufRead *Snakefile set syntax=snakemake
au BufNewFile,BufRead *.smk set syntax=snakemake

call plug#begin('~/.vim/plugged')

Plug 'sheerun/vim-polyglot'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'psf/black', { 'branch' : 'stable' }
Plug 'neoclide/coc.nvim', { 'branch' : 'release' }
Plug 'dhruvasagar/vim-table-mode'
Plug 'sainnhe/gruvbox-material'

call plug#end()

set autoindent
set smartindent

" No .swp file
set noswapfile
" Allow hidden buffers
set hidden
" Show more lines when scrolling
set scrolloff=5

" Line numbering
" Use both for hybrid mode
set number
set relativenumber
" Tab formatting
set smarttab " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
set tabstop=4 " the visible width of tabs
set softtabstop=4 " edit as if the tabs are 4 characters wide
set shiftwidth=4 " number of spaces to use for indent and unindent
set shiftround " round indent to a multiple of 'shiftwidth'
set expandtab

set mouse=a

" Show whitespace characters with :set list
set listchars=tab:→\ ,trail:⋅,extends:❯,precedes:❮,eol:¬,

" Incremental search
set incsearch
" Turn on search highlighting for all results
set hlsearch
" Clear highlighting
nnoremap <silent> <CR> :noh<CR><CR>

" Statusline using airline
" Display nice linestatus
set laststatus=2
" Show status only from airline
set noshowmode
let g:airline_theme = 'bubblegum'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" Use univesal clipboard for copy pasting
set clipboard=unnamedplus

" Highlight column 79 for wrapping code
set colorcolumn=79

" Enable truecolors when using tmux
if exists('+termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
endif

" Set the colorscheme to gruvbox dark
set background=dark
let g:gruvbox_material_background='hard'
let g:gruvbox_material_palette='mix'
"let g:gruvbox_material_palette.dark_blue=['#2c78bf', '18']
let g:gruvbox_material_ui_contrast='high'
let g:gruvbox_material_disable_italic_comment=1
colorscheme gruvbox-material

let g:black_linelength=79


" jk escapes insert mode
inoremap jk <Esc>

"Become a pro
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

" Faster window navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Default split on the right
set splitbelow
set splitright

" Coc Tab completion
function! s:check_back_space() abort
      let col = col('.') - 1
        return !col || getline('.')[col - 1]  =~ '\s'
    endfunction

    inoremap <silent><expr> <Tab>
          \ pumvisible() ? "\<C-n>" :
          \ <SID>check_back_space() ? "\<Tab>" :
          \ coc#refresh()

" Skeletons
autocmd BufNewFile *.py 0r ~/.vim/skeletons/pyscript.py
