alias ls="ls --color=auto"
alias ll="eza -al --group-directories-first --icons=always"
alias rsync="rsync -av --progress"
alias update="sudo apt update && sudo apt upgrade"
alias gs="git status"
alias mamba="micromamba"
alias cat="bat"
